name: 'Archive Newsletter'
description: 'Reusable action to archive newsletters'

inputs:
  date:
    description: 'Date of the newsletter (YYYY-MM-DD)'
    required: true
  category:
    description: 'Category of the newsletter'
    required: true
  repo:
    description: 'Repository to push the changes'
    required: true
  gh_token:
    description: 'GH Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 markdownify

    - name: Run archive script
      shell: bash
      run: |
        python .github/actions/tldr_archive/scripts/archive_newsletter.py ${{ inputs.category }} ${{ inputs.date }}

    - name: Set up GitHub token
      shell: bash
      run: echo "GH_TOKEN=${{ inputs.gh_token }}" >> $GITHUB_ENV

    - name: Commit and push changes
      shell: bash
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add tldr/
        git commit -m "Add newsletter archive for ${{ inputs.date }}"
        git push https://x-access-token:${{ inputs.gh_token }}@github.com/${{ inputs.repo }}.git main || echo "No changes to commit"
